[build]
  base    = "client/"
  publish = "build/"
  command = "CI= npm run build"

[[redirects]]
  from = "/auth/*"
  to = "https://realtimemessenger.herokuapp.com/auth/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://realtimemessenger.herokuapp.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200